---
title: "workshop9"
author: "Paige Lund"
date: "`r Sys.Date()`"
output: html_document
---

#load libraries 

```{r}
#for wrangling and plotting 
library(tidyverse)
#for data access
library(lterdatasampler)
#for models
library(ggeffects)
#for easy file path
library(here)
```


reading in data:
```{r}
data(pie_crab) #reading in plum island ecosystem crab data set from lterdatasampler package
```


exploratory visualization 
```{r}
#set up plot
ggplot(data = pie_crab, 
       aes(x=latitude, y=size)) + 
  #scatterplot and make it blue
  geom_point(color = "skyblue2") + 
  #update axis labels
  labs(x = "Latitude", y = "Size") + 
  #get rid of grid lines 
  theme_minimal()
  


```


writing a model
```{r}
crab_model <- lm(size ~ latitude, #response ~ predictor
                 data = pie_crab) #data from lterdatasampler

#look at diagnostics here
par(mfrow = c(2,2)) # plot diagnostics in 2x2 grid
plot(crab_model)

```

interpret model!
```{r}
#look at results 
summary(crab_model)
```
slope: 0.49 +/- 0.034
y-int: -3.6 +/- 1.27 

for every one unit increase in latitude we expect to see a 0.49 +/- 0.034 increase in crab size

model stats: 
  F(1, 390) = 208.5, p<0.0001, alpha = 0.05, r^2^ = 0.35


